### PR TITLE
Fix $compile:multilink error

### PR DESCRIPTION
**Pull request by ferreiraj-ppb**
**Issue:**
We were doing some tests using this directive inside a ng-repeat directive and we start having [compile errors](https://docs.angularjs.org/error/$compile/multilink) when we had two instances of a react-directive inside a ng-repeat directive.

Demo scenario:
< ng-repeat="item in $ctrl.items track by item.id">
    < react-2-angular-js-directive item="item"/>
< div>

**Investigation/solution:**
After some investigation we found out a possible solution to this problem:
On the [doc error page](https://docs.angularjs.org/error/$compile/multilink) it's referred that:
> "Linking an element as a clone multiple times is ok" 

We found out that sending a `cloneConnectFn` to the `transclude` function call [creates a clone](https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L2468)

Don't know if there's a better solution to solve this issue, but please have a look at it. It worked for all our test scenarios.

### CODE REVIEW

**Comment by fabioatcorreia** [comment]
@ashvin777 can you share your thoughts on this change?

**Comment by ashvin777** [comment]
I would like to understand this issue better, is there any online snippet available which reproduces this issue ?

**Comment by fabioatcorreia** [comment]
https://stackblitz.com/edit/react2angularjs-repeat-issue

image

Let me know if you find this helpful

**Comment by fabioatcorreia** [comment]
did you manage to take a look into this @ashvin777 ?

**Comment by ashvin777** [comment]
@ferreiraj-ppb Please check the conflicts.

**Comment by ferreiraj-ppb** [comment]
@ashvin777 rebase done 👍

**Comment by ashvin777** [comment]
https://www.npmjs.com/package/react2angularjs - released v1.0.2

**Pull request merged**
